# Generated by Django 5.1.6 on 2025-03-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
